
#' Generate the 1st generation of the genetic algorithm
#'
#' @param C Chromosome length
#' @return Matrix, with each column representing a chromosome.

init = function(C){
  #function to generate 1st generation, with C being the chromosome length,
  #i.e. the number of predictors.
  P = min(2*C, 50) #Population size of each generation, 2C would be reasonable with an upper limit.
  gen = replicate(P, sample(c(0,1), size=C, replace=T))
  return(gen)
}

#' Select varuables using the genetic algorithm
#' @param pop
#' @param fit
#' @return list
#' @export

selection = function(pop, dat, criteria=AIC){
  #Selecting parents based on fitness ranks, with AIC as the default fitness criteria.
  #Alternatively, we can use tournament selection.
  #"pop" takes the population matrix, such as the parent generated using init().
  P = ncol(pop) #number of individuals
  fit = rep(1, P) #A vector recording fitness.
  for (i in 1:P){
    chosen = c(which(pop[,i]==1)) #Chosen predictors
    mod = lm(as.formula(paste(colnames(dat)[1], "~",
                              paste(colnames(dat)[chosen+1], collapse = "+"), sep = "")), data=dat)
    ##chosen plus 1 to avoid include response

    fit[i] = -criteria(mod)
    #take negative since we want the one with the lowest AIC has the highest rank.
  }
  fitness = 2*rank(fit)/(P*(P+1)) #A vector of probability weights

  parent_ind = sample(x=1:P, size=P, replace=T, prob=fitness)
  parents = pop[ ,parent_ind]
  #Sample from the P individuals, with weights specified as in fitness, with replacement,
  #to generate a parenting population of size P.
  #Note there are duplicates within the parenting population.

  fittest = pop[,which(fitness==max(fitness))]
  #Keep a copy of the fittest individual.
  return(list(parents, fittest, -fit))#We want positive AIC's
}

mutation = function(ind){#Use fixed rate 0.01
  n = length(ind)
  for (i in 1:n){
    a = sample(1:100, size=1)
    if (a==1){ind[i] = 1 - ind[i]}
    #If mutation happens at one locale, change the 1 at that postition to 0(or 0 to 1).
    else{next}
  }
  return(ind)
}

crossover = function(ind1, ind2){ #Now simply one-point crossover.
  C = length(ind1) #Length of chromosome
  k = sample(1:(C-1), 1) #randomly select a point as the point of crossover.
  ind1_new = mutation(c(ind1[1:k], ind2[(k+1):C]))
  ind2_new = mutation(c(ind2[1:k], ind1[(k+1):C]))
  return(matrix(c(ind1_new, ind2_new), ncol=2))
}


produce = function(pop){#pop is generated using selection()
  #Production from generation t to generation (t+1).
  P = ncol(pop)
  order = sample(1:P, size=P)#Randomly assign paris
  newGen = crossover(pop[,order[1]], pop[,order[2]]) #The first two offspring generated by the first pair of parents.
  for (i in 2:(P/2)){
    newGen = cbind(newGen, crossover(pop[,order[2*i-1]], pop[,order[2*i]]))
  }
  return(newGen)
}

update = function(dat, generations=10, criteria=AIC){#Control maximum generation
  C = ncol(dat) - 1 ##minus y
  pop = init(C)
  fit.val=matrix(0,min(2*C, 50),generations)
  generation.mat=matrix(rep(1:generations,each=min(2*C),50),min((2*C),50),generations)
  for (i in 1:generations){
    sel.result=selection(pop, dat, criteria)
    parents = sel.result[[1]]
    fit.val[,i]=sel.result[[3]]
    pop = produce(parents)
  }
  return(list(pop, selection(pop, dat)[[2]],fit.val))
  #Return two things: a matrix of the last generation; and a listing of the fittest individuals.
  #After 10 generations, the fittest ones are mostly the same, which shows convergence.

}


##One simple test:
#result = update(soccer) #soccer is some local data.
#result[[1]]
##result[[2]]
